# Generated by Django 5.0.3 on 2024-04-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_writer_delete_donorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
