# Generated by Django 5.0.3 on 2024-04-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('story', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
